[package]
name = "bolt-primitives"
description = "Boltchain core types, chain parameters and genesis format"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
alloy-primitives = { workspace = true, features = ["k256"] }
blst.workspace = true
k256 = { version = "0.13", features = ["ecdsa"] }
alloy-rlp.workspace = true
alloy-trie.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true

